CREATE TABLE execution_logs
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    execution_id UUID,
    log_level    VARCHAR(255),
    message      TEXT,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_execution_logs PRIMARY KEY (id)
);

ALTER TABLE execution_logs
    ADD CONSTRAINT FK_EXECUTION_LOGS_ON_EXECUTION FOREIGN KEY (execution_id) REFERENCES job_executions (id);