spring.application.name=distributed_job_scheduler

server.port=19024

spring.datasource.url=jdbc:postgresql://localhost:5432/Job
spring.datasource.username=postgres
spring.datasource.password=tubeo1012

#Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type.json_format_mapper=jackson